num_agents: 4
max_rounds: 2
agent_config:
  num_units: 10
  base_value: 100
  use_llm: true
  initial_cash: 1000
  initial_goods: 0
  good_name: "apple"
  noise_factor: 0.1
  max_relative_spread: 0.2
llm_configs:
#  - name: "hermes-3"
#    client: "vllm"
#    model: "Hermes-3-Llama-3.1-70B"
#    temperature: 0.4
#    max_tokens: 1048
#    use_cache: true
#  - name: "llama-3.1"
#    client: "vllm"
#    model: "Llama-3.1-70B-Instruct"
#    temperature: 0.6
#    max_tokens: 2048
#    use_cache: true
  - name: "claude-3-haiku"
    client: "anthropic"
    model: "claude-3-haiku-20240307"
    temperature: 0.8
    max_tokens: 4096
    use_cache: true
  - name: "gpt-4o-mini"
    client: "openai"
    model: "gpt-4o-mini"
    temperature: 1
    max_tokens: 8192
    use_cache: true
environment_configs:
  auction:
    name: "Apple Market"
    address: "apple_market"
    max_rounds: 100
    good_name: "apple"
protocol: "ACLMessage"
database_config:
  db_type: "postgres"
  db_name: "market_simulation"