num_agents: 8
max_rounds: 2
agent_config:
  num_units: 10
  base_value: 100
  use_llm: true
  initial_cash: 1000
  initial_goods: 0
  good_name: "apple"
  noise_factor: 0.1
  max_relative_spread: 0.2
llm_configs:
  - name: "gpt-4o-mini"
    client: "openai"
    model: "gpt-4o-mini"
    temperature: 1
    max_tokens: 8192
    use_cache: true
#  - name: "qwen2.5"
#    client: "vllm"
#    model: "Qwen2.5-7B-Instruct"
#    temperature: 0.4
#    max_tokens: 512
#    use_cache: true
#  - name: "qwen2.5"
#    client: "vllm"
#    model: "Qwen2.5-7B-Instruct"
#    temperature: 0.6
#    max_tokens: 1048
#    use_cache: true
#  - name: "qwen2.5"
#    client: "vllm"
#    model: "Qwen2.5-7B-Instruct"
#    temperature: 0.8
#    max_tokens: 2048
#    use_cache: true
#  - name: "qwen2.5"
#    client: "vllm"
#    model: "Qwen2.5-7B-Instruct"
#    temperature: 1
#    max_tokens: 4096
#    use_cache: true
environment_configs:
  auction:
    name: "Apple Market"
    address: "apple_market"
    max_rounds: 100
    good_name: "apple"
#  group_chat:
#    name: "Market Group Chat"
#    address: "group_chat"
#    max_rounds: 2
#    initial_topic: "Market Trends"
protocol: "ACLMessage"
database_config:
  db_type: "postgres"
  db_name: "market_simulation"