num_agents: 4
max_rounds: 2
agent_config:
  num_units: 10
  base_value: 100
  use_llm: true
  initial_cash: 1000
  initial_goods: 0
  good_name: "apple"
  noise_factor: 0.1
  max_relative_spread: 0.2
llm_configs:
  - name: "hermes-3"
    client: "vllm"
    model: "Hermes-3"
    temperature: 0.5
    max_tokens: 4096
    use_cache: true
  - name: "llama-3.1"
    client: "vllm"
    model: "llama-3.1-70b"
    temperature: 0.7
    max_tokens: 2048
    use_cache: true
environment_configs:
  auction:
    name: "Apple Market"
    address: "apple_market"
    max_rounds: 100
    good_name: "apple"
protocol: "ACLMessage"
database_config:
  db_type: "postgres"
  db_name: "market_simulation"